[profile.default]
auto_detect_solc = true
bytecode_hash = "none"
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true 
memory_limit = 1073741824 
optimizer_runs = 200

[profile.intense.fuzz]
runs = 10000

[profile.production]
optimizer = true
optimizer_runs = 1000000 
via_ir = true
bytecode_hash = "none"
no_storage_caching = true

[rpc_endpoints]
base_testnet = "${BASE_TESTNET_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"

[etherscan]
base_testnet = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base_mainnet = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

[fuzz]
runs = 1000

[invariant]
runs = 1000
depth = 100
fail_on_revert = false